version: "3.9"
services:
  api:
    image: node
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - ${API_PORT}:3000
    entrypoint: bash -c "npm i && node server.js"

  app:
    image: node
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - ${APP_PORT}:3000
    entrypoint: bash -c "npm i && npm run build && npm start"
