version: "3.9"
services:
  api:
    build: api
    env_file: .env
    ports:
      - ${API_PORT}:3000
    command: node server.js

  app:
    build:
      context: app
      args:
        - URL=${URL}
    env_file: .env
    ports:
      - ${APP_PORT}:3000
    command: npm start
